server:
  port: 0


logging:
  level:
      ROOT: ERROR
      org.example.customer.publisher: DEBUG
      org.springframework: ERROR
      org.springframework.kafka: DEBUG
      io.confluent: DEBUG

pattern:
  console: "%d %-5level %logger : %msg%n"


kafka:
  topic: transaction
  publisher:
    buffer-memory: 33554432
    linger-time-in-ms: 5
    publish-batch-size: 16384
    retry-count: 0
    bootstrap-servers: "localhost:9092"
    schema-registry: http://localhost:8081


#  topic: customer1
#  publisher:
#    buffer-memory: 33554432
#    linger-time-in-ms: 5
#    publish-batch-size: 16384
#    retry-count: 0
#    bootstrap-servers: "localhost:9092"
#    schema-registry: http://localhost:8081




